import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from '@/QueryProvider';
import './globals.css';
import KakaoScript from '@/components/KakaoScript';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KakaoScript />
        <Script
          strategy="beforeInteractive"
          id="naver-map-script"
          type="text/javascript"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env
            .NEXT_PUBLIC_NMAP_KEY!}&submodules=geocoder`}
        />
        <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
        <QueryProvider>
          <main className="w-sm md:w-md m-auto">{children}</main>
          <div id="modal" />
        </QueryProvider>
      </body>
    </html>
  );
}
